[workspace]
members = [
    "crates/plugin-system",
    "crates/plugin-macros",
    "crates/sd-types",
    "crates/sd-events",
    "crates/sd-actions",
    "crates/sd-profiles",
    "crates/sd-devices",
    "crates/sd-paths",
    "crates/sd-api",
    "crates/sd-plugins",
    "crates/sd-core",
    "crates/plugin-cli",
    "crates/plugin-system/tests/cabi-fixture",
    "plugins/plugin-timer",
    "plugins/plugin-system-monitor",
    "plugins/plugin-key-simulator",
    "plugins/plugin-volume-master",
    "plugins/plugin-obs",
]
exclude = [
    "target",
    "data",
    "web",
    "docs",
    "scripts",
    "releases",
]
resolver = "2"
